version: "3.9"

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: newsfeed-backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: newsfeed
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: newsfeed-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: newsfeed-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsfeed
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
